### ISSUE TITLE
mutable borrow leads to trouble

### ISSUE THREAD

**Issue by ggilley** [rajivr/fdb-rl-wip#2]
Hey, in the course of converting to fdb-wip, I ran into an issue. tuple::append takes a mutable reference and modifies the original to be empty. This, of course, caused a bug in my code because I didn't expect it to empty the source. I'm a beginner to rust, so I'm sure I don't have the semantics right, but I think a regular borrow is the right thing here? Since it takes ownership of the value? That way the borrow catcher would have caught the error for me. (Thanks for the great work btw).

**Comment by rajivr** [comment]
> I ran into an issue. tuple::append takes a mutable reference and modifies the original to be empty.

The semantics of [`Tuple::append`](https://rajivr.github.io/fdb-rl-wip/fdb/tuple/struct.Tuple.html#method.append) method is modeled based [`Vec::append`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.append) in the standard library.

In both the cases, the documentation says - Moves the elements of `other` into `self`, leaving `other` empty. This requires `other` to be `&mut`. 

I hope this helps.

**Comment by ggilley** [comment]
LOL, as I said, rust newbie. I have to say I don’t agree with that behavior, but it makes sense to follow the standard library. Sorry for the noise.
